### ISSUE TITLE
Compile exit/entry configuration

### ISSUE THREAD

**Issue by TimJung** [TimJung/Passageway#6]
Make it so when the code is compiled a value of 0 or 1 can be submitted that automatically flips the exit or entry status when a person passes through the beams.

**Comment by JaxonWright** [comment]
this could be handled with command line arguments when running the program after compilation

**Comment by JaxonWright** [comment]
Another possible solution would be to prompt in the terminal to "exit" the door. It would then save that direction as being an exit and the reverse being an entry
